dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "agentic",
    "ansi",
    "breakpoint",
    "coissac",
    "docstrings",
    "dtz",
    "enum's",
    "f'bg",
    "franky",
    "ghostty",
    "ipster",
    "ipython",
    "linenr",
    "noqa",
    "objclass",
    "pdm",
    "plr",
    "plw",
    "pygments",
    "pyproject",
    "pyright",
    "qualname",
    "topline",
    "xdg",
]
